version: '3.1'

volumes:
  apiedmachinedb:
    driver: local

services:

  api-edmachine:
    build:
        context: .
        dockerfile:  docker/api/Dockerfile
    entrypoint: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8090", "--reload"]
    container_name: api-edmachine
    depends_on:
      - db
    env_file:
      - "docker/api/.envvars"
    ports:
      - "8090:8090"
    volumes:
      - ".:/app"

  db:
    container_name: db-api-edmachine
    build:
        context: .
        dockerfile: docker/db/Dockerfile
    env_file:
      - "docker/db/.envvars"
    ports:
      - "3307:3306"
    volumes:
      - apiedmachinedb:/var/lib/mysql
